version: '{branch}-{build}'
build: off
environment:
  global:
    SALT_FILEROOT: '%APPVEYOR_BUILD_FOLDER%'
    SALT_STATE: emet
    SALT_URL: https://repo.saltstack.com/windows/Salt-Minion-2016.11.8-AMD64-Setup.exe
  matrix:
    - SALT_PILLARROOT: '%APPVEYOR_BUILD_FOLDER%\tests\pillar\test-empty'
    - SALT_PILLARROOT: '%APPVEYOR_BUILD_FOLDER%\tests\pillar\test-main'

init:
  - ps: echo $env:PILLAR_HOME
install:
  - ps: |
      $null = `
        (new-object net.webclient).DownloadFile(${env:SALT_URL}, `
        "${env:temp}\salt-minion.exe")
  - ps: |
      $null = `
        Start-Process -FilePath "${env:temp}\salt-minion.exe" `
        -ArgumentList "/S" -NoNewWindow -PassThru -Wait
  - ps: C:\salt\salt-call.bat --versions-report

test_script:
  - ps: |
      C:\salt\salt-call.bat --local --retcode-passthrough `
        --log-file-level debug `
        --file-root="${env:SALT_FILEROOT}" `
        --pillar-root="${env:SALT_PILLARROOT}" `
        state.show_sls `
        "${env:SALT_STATE}"
  - ps: |
      C:\salt\salt-call.bat --local --retcode-passthrough `
        --log-file-level debug `
        --file-root="${env:SALT_FILEROOT}" `
        --pillar-root="${env:SALT_PILLARROOT}" `
        state.sls `
        "${env:SALT_STATE}" `
        mock=True

on_failure:
  - ps: C:\salt\salt-call.bat --local grains.items
  - ps: dir "env:"
  - ps: get-content C:\salt\var\log\salt\*

### To enable remote debugging uncomment this (also, see: http://www.appveyor.com/docs/how-to/rdp-to-build-worker):
# on_finish:
#   - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
